name    'puppet-twemproxy'
version '1.0.2'
source 'UNKNOWN'
author 'wuakitv'
license 'MIT License'
summary 'This modules helps configure Twemproxy.'
description 'This modules compiles from source twemproxy.'
project_page 'https://github.com/wuakitv/puppet-twemproxy'
